version: '3.4'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    volumes:
      - .postgres/database:/var/lib/postgresql/data
      - .postgres/transfer:/var/transfer:rw
      - ./docker_postgres_init_matches.sql:/docker-entrypoint-initdb.d/docker_postgres_init_matches.sql
      - ./docker_postgres_init_stats.sql:/docker-entrypoint-initdb.d/docker_postgres_init_stats.sql
    ports:
      - "5455:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    env_file:
      - .env
